#!/bin/bash

FILE=$(find . -type f -not -path "*/.git/*" -printf "%T@ %p\n" \
| sort -nr \
| head -n 1 \
| cut -d' ' -f2-)

echo "Last modified file: $FILE"

git add "$FILE"
git commit -m "Autoupdate"

while true; do

read -r -p "Push $FILE to GitHub? (y/n): " CONFIRM

confirm=("y" "e" "s" "Y" "E" "S")
deny=("n" "o" "N" "O")

if [[ " ${CONFIRM[*} " == " ${confirm[*]} " ]]; then
git push origin master
echo "$FILE pushed to repo."
break
elif [ " ${CONFIRM[*]} " == " ${deny[*]} " ]]; then
echo "$FILE remains staged, unpushed."
break
elif
echo "Please answer Yes or No."
fi
done
